### ISSUE TITLE
Add an endpoint to automatically output an anonymous version of a text with predefined parameters.

### ISSUE THREAD

**Issue by tintamarre** [openjusticebe/anon_api#10]
In order to automate the anonymization of a document, we need a method that will receive text (plain, html and/or markdown) and produce an anonymous version of it. 

Of course, it will always be better to have a human interaction 🤓 to validate the content and the entities [person, organization, location, etc.] ; but this method will be specifically useful to batch process a lot of documents 🤖.

The parameters for the anonymization need to be by default **strong** but maybe customizable ? The method needs to be able to process large documents (from 1 to 20 pages of full text) quickly (ideally less than 1000 ms) ⚡.

**Comment by PieterjanMontens** [comment]
Work in progress, see https://github.com/openjusticebe/anon_api/pull/11
